### ISSUE TITLE
install.sh gives error "packages/filebrowser-share-file" is not a valid npm package

### ISSUE THREAD

**Issue by Nestak2** [Tubitv/jupyterlab-extensions#4]
I have Ubuntu 18.04. and I am using jupyter lab. I downloaded the repo and ran the as suggested ./scripts/install.sh. It seems that everything runs as expected and the extensions get installed, because the last few lines of output in my terminal say:

```
...
@tubitv/filebrowser-share-file: > @tubitv/filebrowser-share-file@0.1.2-alpha.1 build /home/nestor/Downloads/jupyterlab-extensions-master/packages/filebrowser-share-file
@tubitv/filebrowser-share-file: > tsc -b
@tubitv/filebrowser-deep-copy-paste: > @tubitv/filebrowser-deep-copy-paste@0.1.1-alpha.1 build /home/nestor/Downloads/jupyterlab-extensions-master/packages/filebrowser-deep-copy-paste
@tubitv/filebrowser-deep-copy-paste: > tsc -b
@tubitv/nteract-data-explorer: > @tubitv/nteract-data-explorer@0.1.2-alpha.1 build /home/nestor/Downloads/jupyterlab-extensions-master/packages/nteract-data-explorer
@tubitv/nteract-data-explorer: > tsc -b
lerna success run Ran npm script 'build' in 3 packages in 3.5s:
lerna success - @tubitv/filebrowser-deep-copy-paste
lerna success - @tubitv/filebrowser-share-file
lerna success - @tubitv/nteract-data-explorer
An error occured.
ValueError: "packages/filebrowser-share-file" is not a valid npm package
See the log file for details:  /tmp/jupyterlab-debug-pn9ub673.log
```
So, except for the last 3 lines it all looks fine. When I then do

```
conda activate jupyterlab-ext
jupyter labextension list
```
the tubitv extensions are not shown. What is the problem?

**Comment by fifar** [comment]
@Nestak2 thanks for reporting, will fix it soon.

**Comment by fifar** [comment]
@Nestak2 I tried to reproduce your issue on mac and ubuntu, but couldn't get the same error as yours. I did fix some minor issues during reproduction, see https://github.com/Tubitv/jupyterlab-extensions/pull/6.

Would you mind retrying the repo? And if there are still errors, could you please share the log file?

Besides, after googling I found some similar cases:
- windows specific https://github.com/jupyter-widgets/ipywidgets/issues/1982
- network issue https://github.com/jupyterlab/jupyterlab/issues/6992

I don't know whether these can solve your issue. 

Thanks

**Comment by Nestak2** [comment]
@fifar Thanks for the effort! I retried installing with ./scripts/install.sh and got the same error message. Sorry, I should have provided the log file with the error messages with my original post, [here](https://drive.google.com/file/d/1bjhqC1o3Cdcv_XJHmAasNkXs0w2bDRLg/view?usp=sharing) it is. And [here](https://drive.google.com/file/d/1Vo8KYXU3hwVWJNKaMbOZT1GZCoYQYGCI/view?usp=sharing) is the terminal output.
I am not sure how to interpret the error messages, but the last one says
 
`npm ERR! git@github.com: Permission denied (publickey).
npm ERR! Please make sure you have the correct access rights`

Is this the origin of the problem? The first time I tried installing the extension I also needed to install `npx`, so is there maybe a problem with my version of `npm`? Also, the docs to Tubitv/jupyterlab-extensions state as prerequisite Node.js >=10, but in the virtual environment `jupyterlab-ext` created by ./scripts/install.sh the version is only v8.10.0. Thanks

**Comment by fifar** [comment]
@Nestak2 Could you try `./scripts/install.sh`? I saw you were in the directory `scripts` and executed `./install.sh`. 

And from the logs, you are using your own node and npm, they are `$HOME/anaconda3/bin/node` and `/usr/bin/npm` respectively. So I think npm was installed before node.

**Comment by Nestak2** [comment]
@fifar Uff, I tried `./scripts/install.sh` and it worked indeed, I have the Data Explorer display now working properly. Thanks a lot!!
Suggestion: Wouldn't it make sense to also include the installation of `dx` into the `./scripts/install.sh`, since you can't use the Data Explorer without `dx`?
A short off-topic question: Do you know if one can use the filters for the columns of the Data Explorer not just for exact values, but for a range of values?

**Comment by fifar** [comment]
@Nestak2 Glad you're starting to use nteract data explorer in JupyterLab.

scripts/install.sh installs dx, see [requirements.txt](https://github.com/Tubitv/jupyterlab-extensions/blob/master/scripts/requirements.txt#L3).
btw, dx is not required, but more convenient. Without dx, we can do as follows
```python
import pandas as pd
pd.options.display.html.table_schema = True
df = pd.read_csv('file')
df
```
As for column filters, I'm not sure. I find if a column is numeric, you can filter values by `=`, `>` or `<`. The last two should be more helpful, although not ranges.
